"""
Data models for the AI Communication Workflow.
Defines the state and message structures used throughout the workflow.
"""

from typing import TypedDict, Optional, List, Literal
from dataclasses import dataclass, field


class WorkflowState(TypedDict, total=False):
    """State object that flows through the LangGraph workflow."""

    # Input
    original_message: str
    sender_name: str

    # Generated content
    formal_email_subject: str
    formal_email_body: str
    webex_message: str

    # Recipients
    email_recipients: List[str]
    webex_room_id: str
    webex_mentions: List[str]

    # Human review fields - Email
    email_approved: bool
    email_rejected: bool
    rejection_reason: Optional[str]  # For email rejection

    # Human review fields - Webex
    webex_approved: bool
    webex_rejected: bool
    webex_rejection_reason: Optional[str]

    # General review settings
    requires_human_review: bool

    # Status tracking
    email_sent: bool
    email_error: Optional[str]
    webex_posted: bool
    webex_error: Optional[str]

    # Overall workflow status
    status: Literal[
        "pending",
        "in_progress",
        "awaiting_email_review",
        "awaiting_webex_review",
        "awaiting_review",  # Legacy, kept for compatibility
        "completed",
        "failed",
        "cancelled",
    ]
    errors: List[str]


@dataclass
class EmailContent:
    """Structured email content generated by the LLM."""

    subject: str
    body: str


@dataclass
class WebexMessageContent:
    """Structured Webex message content."""

    text: str
    markdown: str
    mentions: List[str] = field(default_factory=list)

